num_workers: 12
data_dir: data
param_grid: 
  max_depth: [5, 50, 2]
  learning_rate: [0.01, 1, 0.05]
  subsample: [0, 1, 0.05]
  colsample_bytree: [0, 1, 0.05]
  colsample_bylevel: [0, 1, 0.05]
  colsample_bynode: [0, 1, 0.05]
  min_child_weight: [0.5, 10, 1.5]
  gamma: [0.1, 5, 0.05]
  reg_lambda: [0.1, 10, 1.5]
  n_estimators: [50, 500, 10]

fit_params:
  objective: multi:softmax
  eval_metric: merror
  early_stopping_rounds: 10