num_workers: 10

url: https://archive.ics.uci.edu/ml/machine-learning-databases/covtype/covtype.data.gz
random_state: 0
test_size: 0.2
val_size: 0.2

bertable:
  model:
    embedding_dim: 10
    n_layers: 5
    dim_feedforward: 100
    n_head: 10
    dropout: 0.15
    ns_exponent: 0.75
  fit:
    max_epochs: 10
    lr: 0.001
    lr_weight: 
      numerical: 0.3
      categorical: 0.3
      vetor: 0.3
    loss_clip: [0, 100]
    n_sample: 10
    mask_rate: 0.15
    replace_rate: 0.8
    batch_size: 256

param_grid: 
  max_depth: [5, 50, 2]
  learning_rate: [0.01, 1, 0.01]
  subsample: [0, 1, 0.01]
  colsample_bytree: [0, 1, 0.01]
  colsample_bylevel: [0, 1, 0.01]
  colsample_bynode: [0, 1, 0.01]
  min_child_weight: [0.5, 10, 0.5]
  gamma: [0.1, 5, 0.01]
  reg_lambda: [0.1, 10, 0.5]
  n_estimators: [50, 500, 10]

fit_params:
  objective: multi:softmax
  eval_metric: merror